export const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID;
export const APPWRITE_URL = import.meta.env.VITE_APPWRITE_URL;
export const APPWRITE_STORAGE_ID = import.meta.env.VITE_APPWRITE_STORAGE_ID;
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
export const APPWRITE_SAVES_COLLECTION_ID = import.meta.env.VITE_APPWRITE_SAVES_COLLECTION_ID;
export const APPWRITE_POSTS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_POSTS_COLLECTION_ID;
export const APPWRITE_USERS_COLLECTION_ID = import.meta.env.VITE_APPWRITE_USERS_COLLECTION_ID;
